version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: fastburguer-api
    ports:
      - 9080:9080
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fastBurguer?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root     
    links:
      - db

  db:
    image: mysql:latest
    container_name: fastburguer-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always