apiVersion: v1
kind: Service
metadata:
  name: fastburguer-service
spec:
  selector:
    app: fastburguer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9080
  type: NodePort
